// make one target with all tests

// clang-format off
#include "continual.hpp"
#include "recursive.hpp"
#include "regex.hpp"
// clang-format on

// main() will be generated by catch2 (linking with Catch2::Catch2WithMain)
